### ISSUE TITLE
Complete the Program Committee

### ISSUE THREAD

**Issue by RubenVerborgh** [DeSemWeb/iswc2017.desemweb.org#2]
## People to be invited
- [ ] Andreas Harth, Karlsruhe Institute of Technology
- [ ] Sandro Hawke, Massachusetts Institute of Technology
- [ ] Lalana Kagal, Massachusetts Institute of Technology
- [x] Gabriela Montoya, Aalborg University
- [ ] Ilaria Tiddi, Knowledge Media Institute
- [ ] Dmitri Zagidulin, Massachusetts Institute of Technology
- [x] Melvin Carvalho
- [x] Manu Sporny
- [x] John Domingue
- [x] elf Pavlik
- others

## People who confirmed
http://iswc2017.desemweb.org/contributions/#program-committee

**Comment by csarven** [comment]
I'd be happy to contribute provided that:
1) the reviewed work is represented as non-PDF (or any desktop/print-centric format like Word etc.. - I'd presume it'll be available *at least* as HTML [and friends]), and publicly accessible at some URL.
2) the review will be made publicly accessible at an URL of my choice (licensed with CC BY), and refer to the reviewed work's URL.

**Comment by RubenVerborgh** [comment]
Thanks, wishes granted, welcome to the PC! (191f9dcee18a71e182bc898bf44816e2a1f7b4df)

**Comment by rhiaro** [comment]
What @csarven said :)

**Comment by RubenVerborgh** [comment]
Thanks, wishes granted, welcome to the PC! (91f587f4ff366be15b4a92b536838bf1294ec506)

**Comment by RubenVerborgh** [comment]
@deiu @tkuhn Please invite some people from your network and add them to the list above. Can be academy or industry.

**Comment by tkuhn** [comment]
I don't seem to be able to edit the list above, but I suggest the following additional PC members:

- Herbert van de Sompel (Los Alamos)
- Albert Merono (VU Amsterdam)
- Matthew English (Bonn)

I will send invitation emails to them.

**Comment by tkuhn** [comment]
Invitation emails sent. I will try to think of other people to invite...

**Comment by tkuhn** [comment]
Matthew English is in!

**Comment by tkuhn** [comment]
Albert is on board too.

**Comment by RubenVerborgh** [comment]
@tkuhn Thanks; gave you admin rights so you can edit!
